default: &default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>
  pool_size: <%= ENV.fetch("REDIS_POOL_SIZE", 5) %>
  pool_timeout: <%= ENV.fetch("REDIS_POOL_TIMEOUT", 5) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
